#!/usr/bin/expect
#Usage: expect enablelog

spawn ftp 192.168.1.26
expect -re "Name" 
send "root\n"
expect -re "Password"
send "#Pasa3Ford\n"
expect -re "ftp>"
interact
/Users/beyondsoft/Desktop/mac script/logssh/Users/beyondsoft/Desktop/mac script/logssh