#!/usr/bin/expect
#Usage: expect enablelog

spawn ssh root@192.168.1.26
expect -re "password"
send "#Pasa3Ford\n"
expect -re "#"
send "cd /fs/rwdata/Snapshot_Store/tmp\n"
expect -re "#"
send "screenshot\n"
expect -re "#"
send "ls\n"
expect -re "#"
send "exit\n"
interact


set filename screenshot[clock seconds]
spawn ftp 192.168.1.26
expect -re "Name"
send "root\n"
expect -re "Password"
send "#Pasa3Ford\n"
expect -re "ftp>"
send "cd /fs/rwdata/Snapshot_Store/tmp\n"
expect -re "ftp>"
send "get screenshot.bmp $filename.bmp\n"
#send "get screenshot.bmp\n"
expect -re "ftp>"
send "quit\n"
